name: Terraform Tag and Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  terraform-tag-and-release:
    uses: actionsforge/actions/.github/workflows/terraform-tag-and-release.yml@main
